name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
      - name: Unlock git-crypt
        run: |
          sudo apt-get update
          sudo apt-get install -y git-crypt
          echo ${{ secrets.GIT_CRYPT_KEY }} | base64 -d | git-crypt unlock -
      - name: Run tests
        run: sbt test
